"""create core tables

Revision ID: eb135945f6b5
Revises:
Create Date: 2026-09-23 11:38:08.477405

Hand-written (not autogenerated) — this is the first migration against an
empty database, and needs several Postgres/pgvector-specific operations
(extension, HNSW/GIN indexes, RLS) that autogenerate can't reliably produce.
See backend/CLAUDE.md and docs/architecture.md's Schema Management section.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb135945f6b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIMENSIONS = 384  # sentence-transformers/all-MiniLM-L6-v2


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "source_documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("filing_type", sa.String(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("accession_number", sa.String(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("markdown_content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("accession_number"),
    )
    op.create_index("ix_source_documents_ticker", "source_documents", ["ticker"])

    op.create_table(
        "document_chunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIMENSIONS), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', chunk_text)", persisted=True),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["source_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_document_chunk_index"),
    )
    op.create_index("ix_document_chunks_document_id", "document_chunks", ["document_id"])
    # HNSW + GIN are written explicitly (not left to autogenerate) — see backend/CLAUDE.md
    op.create_index(
        "ix_document_chunks_embedding_hnsw",
        "document_chunks",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_document_chunks_search_vector_gin",
        "document_chunks",
        ["search_vector"],
        postgresql_using="gin",
    )

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )

    op.create_table(
        "chat_threads",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chat_threads_user_id", "chat_threads", ["user_id"])

    op.create_table(
        "chat_messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("thread_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role in ('user', 'assistant')", name="ck_chat_messages_role"),
        sa.ForeignKeyConstraint(["thread_id"], ["chat_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chat_messages_thread_id", "chat_messages", ["thread_id"])

    op.create_table(
        "message_citations",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("message_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["chat_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["chunk_id"], ["document_chunks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_message_citations_message_id", "message_citations", ["message_id"])

    # RLS: defense-in-depth for chat data. The backend connects with a direct/service
    # role and bypasses RLS by design (Postgres skips RLS for the table owner and any
    # role with BYPASSRLS) — these policies protect against any future access path
    # that queries Postgres directly as an authenticated user (e.g. PostgREST/anon key).
    # New `users` rows are provisioned by the backend (service role) on first login,
    # not by a client-side insert, so no INSERT policy is defined here.
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE message_citations ENABLE ROW LEVEL SECURITY")

    op.execute("CREATE POLICY users_select_own ON users FOR SELECT USING (auth.uid() = id)")
    op.execute(
        "CREATE POLICY users_update_own ON users FOR UPDATE "
        "USING (auth.uid() = id) WITH CHECK (auth.uid() = id)"
    )
    op.execute(
        "CREATE POLICY chat_threads_owner ON chat_threads FOR ALL "
        "USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)"
    )
    op.execute(
        "CREATE POLICY chat_messages_owner ON chat_messages FOR ALL USING ("
        "  EXISTS (SELECT 1 FROM chat_threads t WHERE t.id = chat_messages.thread_id AND t.user_id = auth.uid())"
        ") WITH CHECK ("
        "  EXISTS (SELECT 1 FROM chat_threads t WHERE t.id = chat_messages.thread_id AND t.user_id = auth.uid())"
        ")"
    )
    op.execute(
        "CREATE POLICY message_citations_owner ON message_citations FOR ALL USING ("
        "  EXISTS (SELECT 1 FROM chat_messages m JOIN chat_threads t ON t.id = m.thread_id "
        "          WHERE m.id = message_citations.message_id AND t.user_id = auth.uid())"
        ") WITH CHECK ("
        "  EXISTS (SELECT 1 FROM chat_messages m JOIN chat_threads t ON t.id = m.thread_id "
        "          WHERE m.id = message_citations.message_id AND t.user_id = auth.uid())"
        ")"
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS message_citations_owner ON message_citations")
    op.execute("DROP POLICY IF EXISTS chat_messages_owner ON chat_messages")
    op.execute("DROP POLICY IF EXISTS chat_threads_owner ON chat_threads")
    op.execute("DROP POLICY IF EXISTS users_update_own ON users")
    op.execute("DROP POLICY IF EXISTS users_select_own ON users")

    op.drop_table("message_citations")
    op.drop_table("chat_messages")
    op.drop_table("chat_threads")
    op.drop_table("users")
    op.drop_table("document_chunks")
    op.drop_table("source_documents")
    # pgvector extension intentionally left installed — dropping shared extensions
    # in a downgrade risks breaking other objects that may depend on it.
